language: php
php:
- 7.1.9

before_script:
- composer self-update
- composer install --prefer-source --no-interaction

# Cache composer packages so "composer install" is faster
cache:
  directories:
  - $HOME/.composer/cache/files

# Run script
script:
  # BDD tests
- ./vendor/bin/phpspec run --config phpspec.travis.yml -vvv
  # coding standards and analysis
- ./vendor/bin/phpcs --standard=PSR2 src
- ./vendor/bin/phpmd src text mess-dector-rules.xml
- ./vendor/bin/phpstan analyse src --level=7